<div data-id="<?php echo $pl->id ?>" class="op-playlist">
    <?php if ( !isset( $embed ) ) : ?>
    <div class="op-playlist-header">
        <div class="op-playlist-header-in">
            <a href="javascript:" 
               class="op-icons op-link-pl-openhide op-fl <? if (isset($this->user->settings['pl'][$pl->id]) && 'true' == $this->user->settings['pl'][$pl->id]): ?>op-icon-open<? else: ?>op-icon-closed<? endif ?>" 
               data-id="<?php echo $pl->id ?>">&nbsp;</a>

            <span id="opLinkPlaylistName<?php echo $pl->id ?>">
                <?php echo $pl->name ?>
            </span>

            <a href="javascript:" data-id="<?php echo $pl->id ?>" class="op-icons op-icon-pl-del op-fr op-link-pl-del">&nbsp;</a>
            <a href="javascript:" data-id="<?php echo $pl->id ?>" class="op-icons op-icon-pl-edit op-fr op-link-pl-edit">&nbsp;</a>
            
            <?php if ( op_conf('widgets', 'downloadTrack') ): ?>
                <a href="<?php echo op_conf('app', 'baseUrl') . '?app=download&query=m3u&plId=' . $pl->id ?>" title="Скачать m3u" class="op-icons op-icon-pl-download op-fr">&nbsp;</a>
            <?php endif; ?>

            <?php if ( op_conf('widgets', 'allowEmbed') ): ?>
                <a href="javascript:" data-id="<?php echo $pl->id ?>" class="op-icons op-icon-pl-embed op-fr op-link-pl-html">&nbsp;</a>
            <?php endif; ?>
        </div>
    </div>
    <?php endif ?>

    <div id="opLinkPlaylistSongs<?php echo $pl->id ?>" class="op-container-songbox <? if (isset($this->user->settings['pl'][$pl->id]) && 'true' == $this->user->settings['pl'][$pl->id]): ?>op-hide<? endif ?>">
        <?php $userCheck = ( !isset($embed) || false == $embed ) ?>
        
        <? foreach ($playlistManager->getSongs($pl->id, $userCheck) as $plSong): ?> 
            <? $song = unserialize($plSong->songInfo) ?>

            <? $plId = $pl->id ?>
            <? $position = $plSong->position ?>

            <? require ROOT . '/views/partials/song.phtml'; ?>
        <? endforeach ?>
    </div>
</div>