<div class="op-song" 
     data-id="<?php echo $song['id'] ?>" 
     data-plid="<?php echo $plId ?>" 
     data-url="<?php echo $song['url'] ?>" 
     data-name="<?php echo $song['name'] ?>" 
     data-uname="<?php echo urlencode($song['name']) ?>" 
     data-artist="<?php echo $song['artist'] ?>" 
     data-uartist="<?php echo urlencode($song['artist']) ?>" 
     data-duration="<?php echo $song['duration'] ?>"
     data-position="<?php echo isset($position) ? $position : null ?>">

    <div class="op-subsong">
        <div class="op-fl">
            <a href="javascript:" class="op-icons op-icon-song-play op-link-song-play">&nbsp;</a>
        </div>

        <div>
            <?php $lim = 50 ?>
            <?php $artist = op_clear($song['artist']) ?>
            <?php $name = op_clear( $song['name'] ) ?>

            <a href="./?q=<?php echo $artist ?>" class="op-atrist"><?php echo op_truncate( $artist, $lim ) ?></a> 
            -
            <?php echo op_truncate( $name, $lim ) ?> 

            (<?php echo $song['duration'] ?>)

            <span class="op-fr op-mouse-hidden">
                <?php
                $subUrl = urlencode(html_entity_decode(trim($song['artist']).'-'.trim($song['name'])));
                $normalUrl = op_conf('app', 'baseUrl') . "?l=1&q=" . $subUrl;
                $url = urlencode($normalUrl);
                $text = urlencode(html_entity_decode($song['artist'].'-'.$song['name'])." #openwebplayer #nowplaying");
                $via = "openwebplayer";
                ?>
                
				<?php if ( op_conf('widgets', 'downloadTrack') ):
                        $_q = http_build_query(array(
                            'app' => 'ajax',
                            'query' => 'dl',
                            'artist' => html_entity_decode(trim($song['artist'])),
                            'name' => html_entity_decode(trim($song['name'])),
                            'id' => $song['id'],
                            'url' => $song['url'],
                        ));
                        $dlUrl = op_conf('app', 'baseUrl').'?'.$_q;
                    ?>
                
                    <a title="<?php echo __('Download') ?>" class="op-icons op-icon-download" href="<?php echo $dlUrl?>">&nbsp;</a>
				<?php endif;?>

                    
                <?php if ( op_conf('widgets', 'directLink') ):?>
                    <a title="<?php echo __('Track link') ?>" class="op-icons op-icon-link" href="javascript:" onclick="prompt('<?php echo __('Track link') ?>', '<?php echo str_replace(' ', '+', urldecode($normalUrl))?>')">&nbsp;</a>
                <?php endif;?>
                    
                <?php if ( op_conf('widgets', 'socialButtons') ):?>
                    |
                    <a title="<?php echo __('Tweet') ?>" class="op-icons op-icon-twitter" target="_blank" href="http://twitter.com/share?via=<?php echo $via?>&url=<?php echo $url?>&text=<?php echo $text?>">&nbsp;</a>
                    <a title="<?php echo __('Share on vkontakte') ?>" class="op-icons op-icon-vk" target="_blank" href="http://vkontakte.ru/share.php?title=<?php echo $text?>&description=<?php echo $text?> <?php echo $url?>">&nbsp;</a>
                    <a title="<?php echo __('Share on facebook') ?>" class="op-icons op-icon-facebook" target="_blank" href="http://www.facebook.com/sharer.php?u=<?php echo $url?>&t=<?php echo $text?> <?php echo $url?>">&nbsp;</a>
                <?php endif ?>
                
                <?php if ( !isset($embed) || false == $embed ): ?>
                    <span class="op-song-del-span <? if (!$plId): ?>op-hide<? endif ?>">
                        |
                        <a href="javascript:" 
                           class="op-link-song-del op-icons op-icon-song-del" 
                           data-id="<?php echo $song['id'] ?>"
                           data-plid="<?php echo $plId ?>">&nbsp;</a>
                    </span>
                <?php endif ?>
                
            </span>
        </div>
    </div>
</div>
