<!DOCTYPE html>
<html>
    <head>
        <title>
            <?php echo ( $this->title ) ? : op_conf('app', 'title') ?>
        </title>
        
        <base href="<?php echo op_conf('app', 'baseUrl') ?>"/>
        
        <meta charset="<?php echo op_conf('app', 'charset') ?>"/>
        
        <script type="text/javascript" src="./web/js/jquery.js"></script>
        <script type="text/javascript" src="./web/js/jquery-ui.js"></script>
        <script type="text/javascript" src="./web/lib/jquery.jplayer.min.js"></script>
        
        <script type="text/javascript" src="./web/js/Loading.js"></script>
        <script type="text/javascript" src="./web/js/Playlists.js"></script>
        <script type="text/javascript" src="./web/js/Base.js"></script>
        
        <link href="./web/css/index.css?v2" rel="stylesheet" media="all" />
        <link href="./web/css/design.css?v2" rel="stylesheet" media="all" />
        <link href="./web/css/jquery-ui.custom.css" rel="stylesheet" media="all" />
        
        <link rel="icon" type="image/png" href="./web/img/icon.png" />
    </head>
    
    <body class="op">
        <script type="text/javascript">
            if ( location.hash.match(/#!/) ) {
                location.href = location.hash.replace("#!", "");
            }
            
            var Settings = <?php echo json_encode(\Lib\Config::getInstance()->getOptions('client'))?>;
            var Lang = {
                __: function( word ) {
                    return ( this.translate[word] )
                        ? this.translate[word]
                        : word;
                },
                
                translate: <?php echo json_encode(Lib\Lang::$translate)?>
            }
            
            var baseUrl = '<?php echo op_conf('app', 'baseUrl') ?>';
        </script>
        
        <?php echo $this->content ?>
        
        <?php if ( op_conf('app', 'GoogleAnalytics') ): ?>
            <script type="text/javascript">
                  var _gaq = _gaq || [];
                  _gaq.push(['_setAccount', '<?php echo op_conf('app', 'GoogleAnalytics') ?>']);
                  _gaq.push(['_trackPageview']);

                  (function() {
                    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                  })();

            </script>
        <?php endif ?>
    </body>
</html>