<?php if ( op_conf('widgets', 'lastSearches') ):?>
    <?php echo $this->render('history') ?>
<?php endif;?>

<?php if ( op_conf('widgets', 'recommendations') ):?>
    <?php echo $this->render('recommendation') ?>
<?php endif;?>

<?php if ( !count($this->songs) ): ?>
    <?php echo __('Nothing found') ?>
<?php else: ?>
    <?php foreach ($this->songs as $song): ?>
        <?php $path = $song['url'] ?>
        <?php $plId = 0 ?>

        <?php require ROOT . '/views/partials/song.phtml' ?>
    <?php endforeach ?>
<?php endif ?>