<div class="op-block-about">
    <?php if ( op_conf('widgets', 'languages') ):?>
        <div>
            <strong><?php echo __("Language") ?>:</strong>
            <?php $langs = op_conf('app', 'availableLangs', array()) ?>

            <?php foreach ($langs as $k => $lang): ?>
                <a class="op-underline" href="./?app=lang&lang=<?php echo $lang ?>"><?php echo __($lang) ?></a> 
                <?php if ( ($k+1) != count($langs) ): ?>&bull; <?php endif ?>
            <?php endforeach ?> 
        </div>
    <?php endif; ?>

    <?php if ( op_conf('widgets', 'discussLinks') ):?>
        <div style="margin-top: 5px;">
            <strong><?php echo __("Player discussion") ?>:</strong>
            <a target="_blank" class="op-underline" href="http://twitter.com/openwebplayer"><?php echo __("Twitter") ?></a> &bull;
            <a target="_blank" class="op-underline" href="https://plus.google.com/100300191451326989757/posts/UDvzX4jkDbG"><?php echo __("G+") ?></a> &bull;
            <a target="_blank" class="op-underline" href="http://vk.com/openwebplayer"><?php echo __("Vkontakte") ?></a> &bull;
            <a target="_blank" class="op-underline" href="http://facebook.com/groups/145224552223981"><?php echo __("Facebook") ?></a> &bull;
            <a target="_blank" class="op-underline" href="https://github.com/uavn/openplayer"><?php echo __("GitHub") ?></a> &bull;
            <a target="_blank" class="op-underline" href="http://habrahabr.ru/blogs/webdev/124313/"><?php echo __("Habrahabr") ?></a>
        </div>
    <?php endif; ?>

    <?php if ( op_conf('widgets', 'donate') ):?>
        <div style="margin-top: 5px;">
            <strong><?php echo __("Donate") ?>:</strong>

            <strong>WMZ:</strong>Z197445365429 &bull;
            <strong>WMR:</strong>R789858449478 &bull;
            <strong>WMU:</strong>U363359317719 &bull;
            <strong><?php echo __("Yandex money") ?>:</strong>41001985742406
        </div>
    <?php endif ?>

    <?php if ( op_conf('widgets', 'friends') ):?>
        <div style="margin-top: 5px;">
            <strong><?php echo __("Friends") ?>:</strong>
            <a class="op-underline" href="http://bonart.org.ua/page/openplayer" title="<?php echo __("Project page") ?>"><?php echo __("Project page") ?></a> 
        </div>
    <?php endif; ?>

    <div style="margin-top: 5px;">
        <?php echo __("Powered by") ?>
        <a href="https://github.com/uavn/openplayer" title="Open Player">Open Player</a>
    </div>
    
    <div style="margin-top: 5px;">
        <strong><?php echo __("For copyriters") ?></strong>:
        <a href="<?php echo op_conf('app', 'baseUrl') ?>" class="op-underline"><?php echo op_conf('app', 'baseUrl') ?></a> <?php echo __("is working on") ?> <a href="https://github.com/uavn/openplayer" class="op-underline">Open Player</a>,
        <?php echo str_replace(
                array(
                    "%contactspage%", 
                    "%vkontakte.ru%"
                ),
                array(
                    '<a href="http://bonart.org.ua/contacts" class="op-underline">' . __("contacts") . '</a>', 
                    '<a href="http://vkontakte.ru" target="_blank" class="op-underline">' . __("vkontakte.ru") .  '</a>'
                ),
                __("using %vkontakte.ru% as base and does not have own music database, and don`t store any music content on own servers. For additional information contact me by contacts from %contactspage% page.")) ?>
        
    </div>
</div>