<h3><?php echo __("Artist calalog") ?></h3>

<style type="text/css">
    .op-catalog a {text-decoration: underline !important;}
</style>

<table class="op-catalog">
    <tr>
        <?php foreach( $this->artists as $key => $atrist ): ?>
            <td>
                <?php $key++ ?>
                <a class="op-atrist" href="./?q=<?php echo $atrist->artist ?>" title="<?php echo __("Listen") ?> <?php echo $atrist->artist ?> <?php echo __("online") ?>"><?php echo trim($atrist->artist) ?></a>
                (<?php echo $atrist->cnt ?>)

                <?php if ( 0 == ($key % op_conf('app', 'catalogColumns', 5)) ): ?>
                    </tr><tr>
                <?php endif ?>
            </td>
        <?php endforeach; ?>
    </tr>
</table>