<?php if ($this->user): ?>
    <?php $playlistManager = new \Manager\Playlist ?>

    <div class="op-container-playlists">
        <? foreach ($this->playlists as $pl): ?>
            <?php require ROOT . '/views/partials/playlist.phtml' ?>
        <? endforeach ?>

        <a href="javascript:" id="opLinkNewPlaylist" class="op-icons op-icon-new"><?php echo __('New playlist') ?></a>
    </div>
<?php endif ?>

<script type="text/javascript">
    Playlists.init();
</script>