<?php if (count($this->recommendations)): ?>

    <?php echo __('Similiar artists') ?>: 
    <?php $atrs = array() ?>
    <?php foreach($this->recommendations as $art => $cnt): ?>
        <?php $arts = htmlspecialchars(trim($art)) ?>
        <?php $atrs[] = '<a href="./?q='.$arts.'" class="op-atrist">'.$arts.'</a>'; ?>
    <?php endforeach ?>
    
    <?php echo join(', ', $atrs) ?>
<?php endif ?>