<? if ( Manager\User::isLoggedIn() ): ?>
    <?php echo __('Logged in as') ?> <b><?php echo Manager\User::getUserOption('login') ?></b> &bull;
    <a href="javascript:" id="opLinkLogout" class="op-underline"><?php echo __('Exit') ?></a>
<? else: ?>
    <?php require ROOT . '/views/partials/auth.phtml' ?>
    <a href="javascript:" id="opLinkLogin" class="op-underline"><?php echo __('Authorise') ?></a>
<? endif ?>   
    
<script src="web/js/User.js" type="text/javascript"></script>